######################################################################
# Automatically generated by qmake (2.01a) jue jul 20 22:49:02 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += joystick.h
FORMS += joystick.ui
SOURCES += joystick.cpp main.cpp
RESOURCES += iconos.qrc
